### PR TITLE
Puppet4

### PR DESCRIPTION
**Pull request by mmerfort**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Here's the travis setup I'm using these days for Puppet v4. No need to test the other ruby versions since Puppetv4 uses the AIO which vendors ruby.

https://github.com/sensu/sensu-puppet/blob/master/.travis.yml

**Comment by bastelfreak** [comment]
In my opinion this is a bad idea. Not everybody wants to use the outdated rub version vendored by puppet. Archlinux for example uses the system-ruby, which is currently 2.4.1. Vox Pupuli honors this, one of our examples is: https://github.com/voxpupuli/puppet-zabbix/blob/master/.travis.yml

**Comment by ghoneycutt** [comment]
Could we reduce the number of supported platforms and kill off 2.0.0 and 2.3.1? I only added 2.3.1 because it was supposed to be the next version of ruby in use. Agree that adding 2.4.x is a good idea, at least to test against the newest version of puppet, since that is what will be coming up next.

We could add the following to the matrix I proposed.

```yaml
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 4"
```

**Comment by bastelfreak** [comment]
sounds good to me.

**Comment by bmjen** [comment]
Replaced by #82

**Pull request closed without merging**
