### PR TITLE
(MODULES-2802) Fix multiple source in gemrc

### PR DESCRIPTION
**Pull request by petems**
Basically the same as #59 but with specs and git commits with reference to Jira ticket

### CODE REVIEW

**Comment by petems** [comment]
Travis failures related to Gemfile, updated in https://github.com/puppetlabs/puppetlabs-ruby/pull/61

**Comment by bmjen** [comment]
@petems can you possibly rebase this with your fix from #61 so we can get a travisci run in before merge?

**Comment by petems** [comment]
@bmjen All done! :+1:

**Comment by bmjen** [comment]
Thanks @petems!

**Pull request merged**
